### ISSUE TITLE
[Feature] Update lint workflow trigger to filter changes on `Multiplaftform` directory

### ISSUE THREAD

**Issue by kibettheophilus** [droidconKE/droidconKeKotlin#330]
**Is your feature request related to a problem? Please describe.**
- Follow discussion on #315 

**Describe the solution you'd like**
- Add a path filter
```
on:
  pull_request:
    branches: [ main ]
    paths:
      - multiplatform/**
```
- Update `codeAnalysis` gradlew commands
```
./gradlew :multiplatform:ktlintFormat && ./gradlew :multiplatform:ktlintCheck && ./gradlew :multiplatform:detekt && ./gradlew :multiplatform:spotlessApply
```

**Describe alternatives you've considered**
- Fixing the lint for the whole codebase.

**Additional context**
N/A
